---
- hosts: myhosts
  connection: local
  name: Disable PXE in NICs
  gather_facts: False

  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    bios_pxe_attributes:
      PxeDev2EnDis: "Disabled"

  tasks:

  - name: Set Bios PXE attributes
    community.general.redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attributes: "{{ bios_pxe_attributes }}"
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: bios_attribute

  # DELL ONLY: Updating BIOS settings requires creating a configuration job
  # to schedule the BIOS update, so comment out below for non-Dell systems.

  - name: Create BIOS configuration job (schedule BIOS setting update)
    community.general.idrac_redfish_command:
      category: Systems
      command: CreateBiosConfigJob
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    when: bios_attribute.changed

  - name: Reboot system to apply new BIOS settings
    community.general.redfish_command:
      category: Systems
      command: PowerReboot
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    when: bios_attribute.changed
