---
- hosts: myhosts
  connection: local
  name: Get BIOS boot order
  gather_facts: False

  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    datatype: BiosBootOrder

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Get device boot order
    community.general.redfish_facts:
      category: Systems
      command: GetBiosBootOrder
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    ansible.builtin.copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
