---
- hosts: myhosts
  connection: local
  name: Set default BIOS settings
  gather_facts: False

  vars:
    ansible_python_interpreter: "/usr/bin/env python"

  tasks:

  - name: Set BIOS default settings
    community.general.redfish_config:
      category: Systems
      command: SetBiosDefaultSettings
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: bios_default

  - name: Reboot system to apply new BIOS settings
    community.general.redfish_command:
      category: Systems
      command: PowerReboot
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    when: bios_default.changed
