---
- hosts: myhosts
  connection: local
  name: Set one-time BIOS boot device
  gather_facts: False

  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    bootdevice: Pxe

  tasks:

  - name: Set one-time boot device to {{ bootdevice }}
    community.general.redfish_command:
      category: Systems
      command: SetOneTimeBoot
      bootdevice: "{{ bootdevice }}"
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: bios_onetimeboot

  - name: Reboot system
    community.general.redfish_command:
      category: Systems
      command: PowerReboot
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    when: bios_onetimeboot.changed
