---
- hosts: myhosts
  connection: local
  name: Set BIOS attributes
  gather_facts: False

  vars:
    bios_attributes:
      SriovGlobalEnable: "Enabled"

  tasks:

  - name: Set BIOS attribute
    community.general.redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attributes: "{{ bios_attributes}}"
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: bios_attribute

  # DELL ONLY: Updating BIOS settings requires creating a configuration job
  # to schedule the BIOS update, so comment out below for non-Dell systems.

  - name: Create BIOS configuration job (schedule BIOS setting update)
    community.general.idrac_redfish_command:
      category: Systems
      command: CreateBiosConfigJob
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    when: bios_attribute.changed

  - name: Reboot system to apply new BIOS settings
    community.general.redfish_command:
      category: Systems
      command: PowerReboot
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    when: bios_attribute.changed
