---
- hosts: myhosts
  connection: local
  name: Insert virtual media and boot once from virtual media
  gather_facts: no

  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    iso_image_url: "https://192.168.10.10/iso/VMware-VMvisor-Installer-7.0.0-15843807.x86_64-DellEMC_Customized-A00.iso"

  tasks:
  - name: Set iDRAC virtual media attach attribute to attached
    community.general.idrac_redfish_config:
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      category: "Manager"
      command: "SetManagerAttributes"
      manager_attributes:
        VirtualMedia.1.Attached: "Attached"

  - name: Get virtual media details
    community.general.redfish_info:
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      category: "Manager"
      command: "GetVirtualMedia"

  - name: Insert ISO image as virtual media device
    community.general.redfish_command:
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      category: "Manager"
      command: "VirtualMediaInsert"
      virtual_media:
        image_url: "{{ iso_image_url }}"
        media_types:
          - CD
          - DVD
    register: result

  - name: set iDRAC attribute for one-time boot from virtual CD
    community.general.idrac_redfish_config:
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      category: "Manager"
      command: "SetManagerAttributes"
      manager_attributes:
        ServerBoot.1.BootOnce: "Enabled"
        ServerBoot.1.FirstBootDevice: "VCD-DVD"

  - name: Restart server to boot from virtual media
    community.general.redfish_command:
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      category: "Systems"
      command: "PowerForceRestart"
