---
- hosts: myhosts
  connection: local
  name: Disable User
  gather_facts: False

  vars:
    ansible_python_interpreter: "/usr/bin/env python"

  tasks:

  - name: Disable user
    community.general.redfish_command:
      category: Accounts
      command: DisableUser
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      account_username: "{{ account_username }}"
