---
- hosts: myhosts
  connection: local
  name: Update user password
  gather_facts: False

  vars:
    ansible_python_interpreter: "/usr/bin/env python"

  tasks:

  - name: Update user password
    community.general.redfish_command:
      category: Accounts
      command: UpdateUserPassword
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      account_username: "{{ account_username }}"
      account_password: "{{ account_password }}"
