
stages:
  - testing

integration_test:
  stage: testing
  image: docker:stable-dind
  services:
    - docker:dind
  tags:
    - IaC
    - Paris
  script:
    - apk update && apk add --no-cache
      python3-dev py3-pip gcc git curl build-base
      autoconf automake py3-cryptography linux-headers
      musl-dev libffi-dev openssl-dev openssh
    - docker info
    - python3 --version
    - python3 -m pip install --ignore-installed -r requirements-dev.txt
    - ansible --version
    - molecule --version
    - export IDRAC_ADDRESS=$IDRAC_ADDRESS
    - export IDRAC_USER=$IDRAC_USER
    - export IDRAC_USER_PASSWORD=$IDRAC_USER_PASSWORD
    - molecule test
  environment:
    name: testing/paris-$CI_COMMIT_REF_NAME
