---
# defaults file for idrac_lifecycle_controller_job

# idrac IP/hostname and credentials
idrac_ip: ""
idrac_user: ""
idrac_password: ""

job_id: ""

command: "{{ command_default }}"

# default - don't modify
command_default: "Info"

# Allowable values - don't modify
command_allowable_values: ["Info", "Delete", "DeleteJobQueue", "DeleteJobQueueForce"]
