---
- hosts: myhosts
  connection: local
  name: Volume Inventory
  gather_facts: False

  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    datatype: VolumeInventory

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Get Volume Inventory
    community.general.redfish_info:
      category: Systems
      command: GetVolumeInventory
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    ansible.builtin.copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
