---
- hosts: myhosts
  connection: local
  name: Inventory
  gather_facts: False

  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    datatype: SystemAll

  tasks:

  - name: Set output file
    include_tasks: create_output_file.yml

  - name: Get Inventory
    community.general.redfish_info:
      category: Systems
      command: all 
      baseuri: "{{ baseuri }}"
      username: "{{ username}}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    ansible.builtin.copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
