---
- hosts: myhosts
  connection: local
  name: Device Firmware Inventory
  gather_facts: False

  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    datatype: FirmwareInventory

  tasks:

  - name: Set output file
    include_tasks: create_output_file.yml

  - name: Get Firmware Inventory
    community.general.redfish_info:
      category: Update
      command: GetFirmwareInventory
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    ansible.builtin.copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
