---
- hosts: myhosts
  connection: local
  name: Sessions
  gather_facts: False

  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    datatype: Sessions

  tasks:

  - name: Set output file
    include_tasks: create_output_file.yml

  - name: Get sessions
    community.general.redfish_info:
      category: Sessions
      command: GetSessions
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    ansible.builtin.copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
