---
- hosts: myhosts
  connection: local
  name: CPU Inventory
  gather_facts: False

  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    datatype: CpuInventory

  tasks:

  - name: Set output file
    include_tasks: create_output_file.yml

  - name: Get CPU Inventory
    community.general.redfish_info:
      category: Systems
      command: GetCpuInventory
      baseuri: "{{ baseuri }}"
      username: "{{ username}}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    ansible.builtin.copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
