---
- hosts: myhosts
  connection: local
  name: Set Mananger timezone
  gather_facts: False

  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    manager_timezone_attributes:
      Time.1.Timezone: "US/Central" 

  tasks:

  - name: Set Manager Timezone to {{ timezone }}
    community.general.idrac_redfish_config:
      category: Manager
      command: SetManagerAttributes
      manager_attributes: "{{ manager_timezone_attributes }}"
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 30 
