---
- hosts: myhosts
  connection: local
  name: Set Manager NTP settings
  gather_facts: False

  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    manager_ntp_attributes:
      NTPConfigGroup.1.NTPEnable: "Enabled"
      NTPConfigGroup.1.NTP1: "ntp.us.dell.com"

  tasks:

  - name: Enable NTP
    community.general.idrac_redfish_config:
      category: Manager
      command: SetManagerAttributes
      manager_attributes: "{{ manager_ntp_attributes }}"
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 15

  # Add more NTP servers as needed
  # To get exact attributes names, run the getattributes task first
