---
- hosts: myhosts
  connection: local
  name: Set Manager DNS settings
  gather_facts: False

  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    manager_attributes:
      IPv4Static.1.DNS1: 192.168.0.10
      NICStatic.1.DNSDomainName: mydomain.com

  tasks:

  - name: Configure Static DNS Settings and Domain Name
    community.general.idrac_redfish_config:
      category: Manager
      command: SetManagerAttributes
      manager_attributes: "{{ manager_attributes }}"
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
