---
# tasks file for ome_device_inventory

# assert that either a device ID or service tag or a group name is defined
- name: check for mandatory arguments
  ansible.builtin.assert:
    that:
      - (device_id is defined and device_id) or (device_service_tag is defined and device_service_tag|length > 0) or (ome_group_name is defined and ome_group_name|length > 0)
    fail_msg: "Missing required arguments. Either 'device_id' or 'device_service_tag' or 'ome_group_name' must be defined."

- name: check for mutually exclusive arguments
  block:
    - ansible.builtin.assert:
        that:
          - device_service_tag is not defined
          - ome_group_name is not defined
        fail_msg: "['device_id', 'device_service_tag', 'ome_group_name'] are mutually exclusive arguments."
      when: device_id is defined and device_id

    - ansible.builtin.assert:
        that:
          - device_id is not defined
          - ome_group_name is not defined
        fail_msg: "['device_id', 'device_service_tag', 'ome_group_name'] are mutually exclusive arguments."
      when: device_service_tag is defined and device_service_tag|length > 0

    - ansible.builtin.assert:
        that:
          - device_id is not defined
          - device_service_tag is not defined
        fail_msg: "['device_id', 'device_service_tag', 'ome_group_name'] are mutually exclusive arguments."
      when: ome_group_name is defined and ome_group_name|length > 0

- name: "Run device inventory task for group {{ ome_group_name }}"
  include: ome_device_group_inventory.yml
  when: ome_group_name is defined and ome_group_name|length > 0

- name: "Run device inventory task for service tag {{ device_service_tag }}"
  include: ome_device_inventory.yml
  when: device_service_tag is defined and device_service_tag|length > 0

- name: "Run device inventory task for device ID {{ device_id }}"
  include: ome_device_inventory.yml
  when: device_id is defined and device_id
