---

- name: boot to network ISO
  dellemc.openmanage.idrac_os_deployment:
    idrac_ip: "{{ idrac_ip }}"
    idrac_user: "{{ idrac_user }}"
    idrac_password: "{{ idrac_password }}"
    share_name: "{{ share_name }}"
    iso_image: "{{ iso_image }}"
    expose_duration: "{{ expose_duration }}"
  register: boot_to_network_iso_status
  delegate_to: localhost
  tags:
    - "{{ command }}"
    - "{{ command | lower }}"
