---

- name: find the URL for the DellOSDeploymentService
  ansible.builtin.uri:
    url: "https://{{ idrac_ip }}/redfish/v1/Systems/System.Embedded.1"
    user: "{{ idrac_user }}"
    password: "{{ idrac_password }}"
    method: GET
    headers:
      Accept: "application/json"
      OData-Version: "4.0"
    status_code: 200
    validate_certs: "{{ validate_certs }}"
    force_basic_auth: "{{ force_basic_auth }}"
  register: result
  delegate_to: localhost
  tags:
    - "{{ command }}"

- name: find the URL for the DellOSDeploymentService
  ansible.builtin.set_fact:
    idrac_osd_service_url: "{{ result.json.Links.Oem.Dell.DellOSDeploymentService['@odata.id'] }}"
  when:
    - result.json.Links.Oem.Dell.DellOSDeploymentService is defined
  tags:
    - "{{ command }}"

