---
- hosts: myhosts
  connection: local
  name: Chassis Thermals 
  gather_facts: False

  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    datatype: ChassisThermals

  tasks:

  - name: Set output file
    include_tasks: create_output_file.yml

  - name: Get chassis thermals
    ansible.builtin.redfish_info:
      category: Chassis
      command: GetChassisThermals
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    ansible.builtin.copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
