---
- hosts: myhosts
  connection: local
  name: Manage Indicator LED
  gather_facts: False

  vars:
    ansible_python_interpreter: "/usr/bin/env python"

  tasks:

  - name: Blink LED
    community.general.redfish_command:
      category: Chassis
      command: IndicatorLedBlink
      baseuri: "{{ baseuri }}"
      username: "{{ username}}"
      password: "{{ password }}"
