---

- name: Get target SSL certificate information
  community.crypto.get_certificate:
    host: "{{ idrac_ip }}"
    port: "{{ idrac_https_port }}"
  register: target_certificate
  delegate_to: localhost

- name: Create temporary directory for further use
  ansible.builtin.tempfile:
    state: directory
    suffix: "-certificate"
  register: tempdir
  delegate_to: localhost
  changed_when: False

- name: Save target SSL certificate
  ansible.builtin.copy:
    content: "{{ target_certificate.cert }}"
    dest: "{{ tempdir.path }}/target-cert.pem"
  delegate_to: localhost
  changed_when: False

- name: Parse target SSL certificate info
  community.crypto.x509_certificate_info:
    path: "{{ tempdir.path }}/target-cert.pem"
  register: target_certificate_info
  when: ansible_version.full is version('2.10', '>=')

- name: Parse target SSL certificate info
  ansible.builtin.openssl_certificate_info:
    path: "{{ tempdir.path }}/target-cert.pem"
  register: target_certificate_info
  when: ansible_version.full is version('2.10', '<')

