---
# tasks file for idrac_certificate

- ansible.builtin.assert:
    that:
      - (command|lower) in (idrac_certificate_command_allowable_values|lower)
    fail_msg: "Invalid value '{{ command }}' for argument 'command'. Valid values are {{ idrac_certificate_command_allowable_values }}."

- name: certificate info
  include: idrac_ssl_certificate_info.yml
  when: (command|lower) == "info"

- name: generate CSR
  include: idrac_generate_ssl_csr.yml
  when: (command|lower) == "generatesslcsr"

- name: import SSL certificate
  include: idrac_import_ssl_certificate.yml
  when: (command|lower) == "importsslcertificate"

- name: export SSL certificate
  include: idrac_export_ssl_certificate.yml
  when: (command|lower) == "exportsslcertificate"

- name: restore iDRAC web-server ssl certificate to factory default
  include: idrac_ssl_reset_cfg.yml
  when: (command|lower) == "sslresetcfg"
