---
- hosts: myhosts
  connection: local
  name: Manage System Power - Force Off
  gather_facts: False

  vars:
    ansible_python_interpreter: "/usr/bin/env python"

  tasks:

  - name: Turn system power off
    community.general.redfish_command:
      category: Systems
      command: PowerForceOff
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
