---
# This is an example playbook to execute Ansible tests.

- name: Cleanup
  hosts: all
  gather_facts: no
  collections:
    - dellemc.openmanage
  tasks:

    - name:  Get target SSL certificate information
      delegate_to: jump-host
      get_certificate:
        host: "{{ idrac_address }}"
        port: "{{ idrac_https_port }}"
      register: target_certificate

    - name: Create temporary directory for further use
      delegate_to: localhost
      tempfile:
        state: directory
        suffix: "-certificate"
      register: tempdir

    - name: Save target SSL certificate
      copy:
        content: "{{ target_certificate.cert }}"
        dest: "{{ tempdir.path }}/target-cert.pem"
      delegate_to: localhost

    - name: Parse target SSL certificate info
      delegate_to: localhost
      openssl_certificate_info:
        path: "{{ tempdir.path }}/target-cert.pem"
      register: target_certificate_info

    - name: Unpack PKCS12 certificate to PEM
      delegate_to: localhost
      openssl_pkcs12:
        action: parse
        src: "{{ certificate_file }}"
        path: "{{ tempdir.path }}/unpacked-cert.pem"
        password: "{{ pkcs12_password | or omit }}"
        state: present
      register: certificate_pem
      when: certificate_format == "PKCS12"

    - name: Set path for pem certificate file
      set_fact:
        certificate_pem: "{{ certificate_file }}"
      when: certificate_format == "PEM"

    - name: Set path for pem certificate file
      set_fact:
        certificate_pem: "{{ certificate_pem.filename }}"
      when: certificate_format == "PKCS12"

    - name: Parse local SSL certificate info
      delegate_to: localhost
      openssl_certificate_info:
        path: "{{ certificate_pem }}"
      register: local_certificate_info

    - name: Assert that changes where made
      assert:
        that:
        - target_certificate_info.public_key == local_certificate_info.public_key
        - target_certificate_info.issuer == local_certificate_info.issuer
        - target_certificate_info.subject == local_certificate_info.subject
        - target_certificate_info.not_after == local_certificate_info.not_after
        - target_certificate_info.not_before == local_certificate_info.not_before
